name: CI workflow

# Events
on: push

# List of jobs
jobs:
  test:
    #runner
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [14.x, 16.x, 18.x]
gi
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js ${{matrix.node-version}}
        uses: action/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Install dependecies
        run: npm install

      - name: Run the tests
        run: npm test
