name: CI workflow

# Events
on: push

# List of jobs
jobs:
  test:
    #runner
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [20.x]

    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js ${{matrix.node-version}}
        uses: action/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependecies
        run: npm install

      - name: Run the tests
        run: npm test
