name: CI workflow

# Events
on: push

# List of jobs
jobs:
  test:
    #runner
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [16.x]

    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js ${{matrix.node-version}}
        uses: action/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
