name: CI workflow

# Events
on: push

# List of jobs
jobs:
  test:
    #runner
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [18]

    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
